[package]
name = "nt-stub-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.27", features = ["derive"] }
lagan = "0.1.0"
log = "0.4.25"
simplelog = "0.12.2"
crossterm = "0.28.1"
eframe = "0.31.0"
egui_extras = { version = "0.31.0", features = ["image"] }
