[target.aarch64-unknown-linux-gnu]
linker = "aarch64-unknown-linux-gnu-gcc"
# Make sure that the pi uses a real linker
rustflags = [
    "-C", "link-arg=-Wl,--dynamic-linker=/lib/ld-linux-aarch64.so.1"
]